# Generated by Django 6.0.2 on 2026-03-03 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_asset_purchase_cost_asset_purchased_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('technician_name', models.CharField(max_length=200, verbose_name='Technician Name')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='Alternate Phone')),
                ('address', models.TextField(blank=True, verbose_name='Physical Address')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Specialization/Expertise')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
                'ordering': ['company_name', 'technician_name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Role/Position')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='technicians.technician')),
            ],
            options={
                'verbose_name': 'Technician Assistant',
                'verbose_name_plural': 'Technician Assistants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('REPAIR', 'Repair'), ('REPLACE', 'Replace'), ('UPGRADE', 'Upgrade'), ('MAINTENANCE', 'Regular Maintenance'), ('DISPOSE', 'Dispose'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(verbose_name='Recommendation Details')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimated Cost (KES)')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_recommendations', to='assets.asset')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='technicians.technician')),
            ],
            options={
                'verbose_name': 'Technician Recommendation',
                'verbose_name_plural': 'Technician Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Service/Repair Name')),
                ('description', models.TextField(blank=True)),
                ('typical_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Typical Cost (KES)')),
                ('estimated_duration', models.CharField(blank=True, max_length=100, verbose_name='Estimated Duration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='technicians.technician')),
            ],
            options={
                'verbose_name': 'Technician Service',
                'verbose_name_plural': 'Technician Services',
                'ordering': ['service_name'],
            },
        ),
    ]
