# Generated by Django 6.0.2 on 2026-03-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianservice',
            name='estimated_duration',
        ),
    ]
