# Generated by Django 6.0.2 on 2026-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_remove_technicianservice_estimated_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianrecommendation',
            name='asset',
        ),
        migrations.AddField(
            model_name='technicianrecommendation',
            name='category_name',
            field=models.CharField(blank=True, help_text='e.g. Laptops, Printers, Network Switch', max_length=200, verbose_name='Category / Item (optional)'),
        ),
    ]
