# Generated by Django 5.0.2 on 2026-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='req_no',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Requisition No.'),
        ),
    ]
