# Generated by Django 5.0.2 on 2026-02-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0002_alter_requisition_req_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Reason (if not approved)'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold'), ('Bought', 'Bought')], db_index=True, default='Pending', max_length=20),
        ),
    ]
