# Generated by Django 6.0.2 on 2026-03-03 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_requisitionitem_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='company',
            field=models.CharField(choices=[('Tera', 'Tera'), ('Flux', 'Flux'), ('Tamuwa', 'Tamuwa')], default='Tamuwa', max_length=20, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Processed'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='item_type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Service', 'Service')], default='Asset', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='req_no',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Requisition No.'),
        ),
        migrations.AlterUniqueTogether(
            name='requisition',
            unique_together={('req_no', 'company')},
        ),
    ]
