# Generated by Django 6.0.2 on 2026-03-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0004_requisition_company_requisitionitem_is_processed_and_more'),
    ]

    operations = [
    ]
