# Generated by Django 6.0.2 on 2026-03-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_remove_issue_requisition_remove_project_requisitions'),
        ('requisition', '0005_auto_20260303_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='linked_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='issues.issue', verbose_name='Linked Issue'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='linked_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='issues.project', verbose_name='Linked Project'),
        ),
    ]
