# Generated by Django 5.0.2 on 2026-02-24 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_purchase_cost_asset_purchased_from_and_more'),
        ('issues', '0001_initial'),
        ('requisition', '0003_requisitionitem_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_type',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolved_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='target_date',
        ),
        migrations.AddField(
            model_name='issue',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='requisition.requisition'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Monitoring', 'Monitoring'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, help_text='Project start or target date', null=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('cost_breakdown', models.TextField(blank=True, help_text='e.g. "Monitors x5 @ KES 20,000 = KES 100,000"')),
                ('conclusion', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('pending_reason', models.TextField(blank=True, help_text='Required when status is Pending')),
                ('rejected_reason', models.TextField(blank=True, help_text='Required when status is Rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Link asset categories to show available quantities', related_name='projects', to='assets.category')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_projects', to=settings.AUTH_USER_MODEL)),
                ('requisitions', models.ManyToManyField(blank=True, related_name='projects', to='requisition.requisition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
