# Generated by Django 6.0.2 on 2026-03-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_remove_issue_assigned_to_remove_issue_issue_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Asset', 'Asset'), ('Service', 'Service')], default='Asset', max_length=10)),
                ('item_name', models.CharField(max_length=200, verbose_name='Item / Service')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='issues.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
