# Generated by Django 6.0.2 on 2026-03-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_projectitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requisitions',
        ),
    ]
