# Generated by Django 5.0.2 on 2026-02-16 09:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='assets_cate_name_98aff4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='assets_depa_name_7185c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='assets_stat_name_58aa69_idx')],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('model_description', models.CharField(max_length=200, verbose_name='Model / Description')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('admin_comments', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('last_known_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_known_assets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.category')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.department')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.statusoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('ASSIGN', 'Assigned'), ('UNASSIGN', 'Unassigned'), ('STATUS_CHANGE', 'Status Changed'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='assets.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', 'timestamp'], name='assets_acti_asset_i_fe28c4_idx'), models.Index(fields=['user', 'timestamp'], name='assets_acti_user_id_cf801b_idx'), models.Index(fields=['action', 'timestamp'], name='assets_acti_action_08f343_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='assets.asset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assignment Histories',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['asset', 'start_date'], name='assets_assi_asset_i_d8ccad_idx'), models.Index(fields=['user', 'start_date'], name='assets_assi_user_id_a51bf1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_id'], name='assets_asse_asset_i_501f65_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='assets_asse_serial__401a52_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status__1c67a8_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['assigned_to'], name='assets_asse_assigne_8034d6_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_deleted'], name='assets_asse_is_dele_7f20a7_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'serial_number'], name='assets_asse_categor_14bd6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('category', 'serial_number'), name='unique_serial_per_category'),
        ),
    ]
