# Generated by Django 5.0.2 on 2026-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='category',
            name='short_code',
            field=models.CharField(blank=True, help_text='e.g. MSE for Mouse', max_length=10, null=True, unique=True),
        ),
    ]
