# Generated by Django 6.0.2 on 2026-02-23 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_qr_code_category_short_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                Person := apps.get_model('assets', 'Person'),
                User := apps.get_model('auth', 'User'),
                [Person.objects.get_or_create(
                    id=u.id, 
                    defaults={
                        'first_name': u.first_name or u.username, 
                        'last_name': u.last_name or '',
                    }
                ) for u in User.objects.all()]
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveIndex(
            model_name='assignmenthistory',
            name='assets_assi_user_id_a51bf1_idx',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_known_user',
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='assets.department'),
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='assets.department'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_known_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_known_assets', to='assets.person'),
        ),
        migrations.AddField(
            model_name='assignmenthistory',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='assets.person'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='assets.person', verbose_name='Assigned To'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['department'], name='assets_asse_departm_eda949_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmenthistory',
            index=models.Index(fields=['person', 'start_date'], name='assets_assi_person__27ac1b_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmenthistory',
            index=models.Index(fields=['department', 'start_date'], name='assets_assi_departm_82654c_idx'),
        ),
        migrations.RemoveField(
            model_name='assignmenthistory',
            name='user',
        ),
    ]
