# Generated by Django 5.0.2 on 2026-02-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_person_and_more'),
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase Cost'),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=200, verbose_name='Purchased From (Vendor)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='requisition.requisition', verbose_name='Requisition No.'),
        ),
    ]
