# Generated by Django 5.0.2 on 2026-03-09 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_purchase_cost_asset_purchased_from_and_more'),
        ('requisition', '0006_requisition_linked_issue_requisition_linked_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_serial_per_category',
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('serial_number__iexact', 'n/a'), _negated=True), models.Q(('serial_number__iexact', 'generic'), _negated=True)), fields=('category', 'serial_number'), name='unique_serial_per_category'),
        ),
    ]
