# Generated by Django 5.0.2 on 2026-03-15 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_update_unique_serial_exclude_na_generic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linked_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='assets.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset'], name='assets_asse_asset_i_eb7e9a_idx'), models.Index(fields=['linked_asset'], name='assets_asse_linked__4885e8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assetlink',
            constraint=models.UniqueConstraint(fields=('asset', 'linked_asset'), name='unique_asset_link'),
        ),
    ]
