# Generated by Django 6.0.2 on 2026-02-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_person_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancelog',
            name='previous_assigned_user',
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='previous_assigned_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='assets.person'),
        ),
    ]
