# Generated by Django 5.0.2 on 2026-02-24 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_purchase_cost_asset_purchased_from_and_more'),
        ('maintenance', '0002_rename_previous_assigned_user_to_person'),
        ('requisition', '0002_alter_requisition_req_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to='assets.person', verbose_name='Performed By'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='requisition.requisition', verbose_name='Requisition No.'),
        ),
    ]
