# Generated by Django 6.0.2 on 2026-03-03 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancelog_performed_by_and_more'),
        ('technicians', '0002_remove_technicianservice_estimated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='technicians.technician', verbose_name='Performed By'),
        ),
    ]
