# Generated by Django 5.0.2 on 2026-03-15 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenancelog_performed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Maintenance Date/Time'),
        ),
    ]
